title: Jeff Karl
logo: /ProfilePictureRound.jpg
description: Curious - Friendly - Reliable - Innovative
#show_download: true
Download Jeff's Resume: /jeffkarl/portfolio/Resume Business Data Analyst Jeff Karl 2024.pdf
theme: jekyll-theme-minimal
